---
  user: seed
  passwd: password123
  domain: testcloudbox.ml
  email: your@email.com
  nzbget:
    downloads: "/home/{{user}}/downloads/nzbget"
  deluge:
    vpn_enabled: yes
    vpn_provider: pia
    vpn_location: Netherlands
    vpn_user: username
    vpn_password: password
    downloads: "/home/{{user}}/downloads/deluge"
  plex:
    tag: public
    transcodes: "/home/{{user}}/transcodes"
  plex_autoscan:
    ip: "0.0.0.0"
  rclone:
    version: 1.38
  unionfs_cleaner:
    max_local_gigabytes: 200
    size_check_mins: 30
    rclone_local_final: "gfinal:"
    rclone_local_decrypt: "gdcrypt:"
  backup:
    tar_dest: "/home/{{user}}/Backups"
    rsync_dest: rsync://somehost.com/Backups
    rclone_dest: google:/Backups
    use_rsync: false
    use_rclone: false
    cron_time: weekly
    cron_state: absent
    pushover_app_token:
    pushover_user_key:
